name: Create Cluster

on:
  workflow_dispatch:
  repository_dispatch:
    types: create-cluster
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - shell: bash
        working-directory: ./infra
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
        run: |
          echo "$PRIVATE_KEY" > secrets/id_ed25519_lfd259
          echo "$PUBLIC_KEY" > secrets/id_ed25519_lfd259.pub
          echo "$TOKEN_GITHUB" > secrets/token_github

      - name: Permissions
        working-directory: ./infra
        run: chmod 600 secrets/id_ed25519_lfd259
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: TF Init
        working-directory: ./infra
        run: terraform init
        
      - name: TF Create
        working-directory: ./infra
        run: terraform apply -var="hcloud_token=${{secrets.TOKEN_HETZNER}}" -auto-approve   
          
      - name: Extract MasterIpv4 Address
        working-directory: ./infra
        run: terraform output master_ip
