name: Test Output

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Set MasterIpv4 Address
        working-directory: ./infra        
        id: terraform-output
        run: echo "::set-output name=master_ip::test123"
          
      - name: Echo output value
        working-directory: ./infra   
        run: echo ${{ steps.terraform-output.outputs.master_ip }}

      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MASTER_IP'
          value: ${{ steps.terraform-output.outputs.master_ip }}
