name: Teardown Cluster

on:
  workflow_dispatch:
  repository_dispatch:
    types: teardown
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: TF Init
        working-directory: ./infra
        run: terraform init
